name: Test images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v7
      with:
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:apptainer/ppa
        sudo apt-get update
        sudo apt-get install -y apptainer

    - name: Build images
      run: |
        echo "Free space:"
        df -h
        prefix=Apptainer.
        for recipe in $prefix* ; do
            name="${recipe#$prefix}".sif
            apptainer build ${name} ${recipe}
            rm ${name}
        done

    # Disabled since we can only store 500 MB.
    #- name: Upload artifacts
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: images
    #    path: "*.sif"
