name: Test images

on: [push, pull_request]

jobs:
  build:
    if: github.repository != 'ipc2023-learning/scripts'
    runs-on: ubuntu-22.04

    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@v1.2.0
      with:
        # This might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB.
        tool-cache: true

        # All of these default to true.
        android: true
        dotnet: true
        haskell: true
        large-packages: false  # deletion is slow
        swap-storage: true

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:apptainer/ppa
        sudo apt-get update
        sudo apt-get install -y apptainer

    - name: Free space
      run: |
        echo "Free space"
        df -h

    - name: Build images
      run: |
        prefix=Apptainer.
        for recipe in $prefix* ; do
            name="${recipe#$prefix}".sif
            apptainer build ${name} ${recipe}
            rm ${name}
        done

    # Disabled since we can only store 500 MB.
    #- name: Upload artifacts
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: images
    #    path: "*.sif"
