name: Test images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:apptainer/ppa
        sudo apt-get update
        sudo apt-get install -y apptainer

    - name: Free space
      run: |
        echo "Free space before:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        echo "Free space after:"
        df -h

    - name: Build images
      run: |
        prefix=Apptainer.
        for recipe in $prefix* ; do
            name="${recipe#$prefix}".sif
            apptainer build ${name} ${recipe}
            rm ${name}
        done

    # Disabled since we can only store 500 MB.
    #- name: Upload artifacts
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: images
    #    path: "*.sif"
